name: C/C++ Release candidate macos

on:
  push:
    branches:
      - rc

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'rc'
    - name: build deps & slicer
      run: ./BuildMacOS.sh -i
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rc_macos.app
        path: build/pack/SuperPleccer/SuperPleccer.app
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: rc_macos.dmg
        path: build/SuperPleccer.dmg
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: SuperPleccer-${{ matrix.config.os }}
        asset_path: build/SuperPleccer.dmg
        asset_content_type: application/octet-stream
